apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        metadata:
          name: cron-pod
        spec:
          containers:
          - name: ubuntu
            image: ubuntu
          restartPolicy: Never