apiVersion: batch/v1
kind: Job
metadata:
  name: adder
spec:
  completions: 3 #corresponds to replicas
  parallelism: 3 #creates the pods in parallel
  template:
    spec:
      metadata:
        name: adder-container
      containers:
      - image: ubuntu
        name: ubuntu-os
        command: ["expr", "5", "+", "3"]
      resetartPolicy: Never

# The job continues to create new pods until the required completion count is reached