apiVersion: v1
kind: Pod
metadata:
  name: resource
  labels:
    type: demo
spec:
  containers:
  - image: nginx
    name: demo-container
    resources:
      requests:
        memory: "1Gi"
        CPU: 1
      limits:
        memory: "2Gi"