apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    type: front-end
spec:
  containers:
    - name: nginx
      image: nginx
      command: ["sleep", 1000"]
      securityContext: #supported at Pod, and Comtainer level
        runAsUser: 1000
        capabilities: # supported only at container level
          add: ["MAC_ADMIN"] 